- host: 127.0.0.1
  port: 3306
  username: root
  password: root
  charset: utf8mb4
  dbname: faker
  tables:
    - table: news
      flag: 1-news
      fields:
        id: INT NOT NULL AUTO_INCREMENT
        created_at: datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
        updated_at: datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
        deleted_at: datetime DEFAULT NULL COMMENT '删除时间'
        index:
          - PRIMARY KEY (id)
        other:
          - ENGINE=InnoDB
          - DEFAULT
          - CHARSET=utf8mb4
      rules:
        id:
          func: id_auto_increment
          database: faker
          table: news

    - table: news_content
      flag: 2-news_content
      fields:
        id: int NOT NULL AUTO_INCREMENT
        news_id: int NOT NULL COMMENT '新闻关联id'
        name: varchar(30) DEFAULT '' COMMENT '名称'
        img: varchar(256) DEFAULT '' COMMENT '文章图片'
        content: text COMMENT '文章内容'
        lang: tinyint DEFAULT '1' COMMENT '1.中文 2.英文'
        created_at: datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
        updated_at: datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
        deleted_at: datetime DEFAULT NULL COMMENT '删除时间'
        index:
          - PRIMARY KEY (id)
        other:
          - ENGINE=InnoDB
          - DEFAULT
          - CHARSET=utf8mb4

      rules:
        news_id:
          func: cell_conversion
          flag: 1-news
          name: id
        name:
          func: faker|name
        img:
          func: default_random
          array:
            - uploads/Ey3753aMp6lTxGZPnTMPx84xVlIPrb35RIBCV7Ny.jpg
            - uploads/Ey3753aMp6lTxGZPnTMPx84xVlIPrb35RIBCV7Ny.jpg

        content:
          func: date_range
          start: 2021-05-01
          end: 2021-05-31
          res_format: '%Y-%m-%d'
          step: DAY_TO_SECOND

      lines: [ 1-news, 2-news_content ]
      number: 10
      chunk: 1
