-
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  charset: utf8mb4
  dbname: faker
  databases:
    -
      table: faker
#      fields:
#        id: INT NOT NULL AUTO_INCREMENT
#        name: VARCHAR(20) NOT NULL
#        date: timestamp NOT NULL
#        index:
#          - PRIMARY KEY (id)
#        other:
#          - ENGINE=InnoDB
#          - DEFAULT
#          - CHARSET=utf8mb4

      rules:
        date:
          func: range_date
          start: '2019-07-20'
          end: '2019-08-20'
          res_format: '%Y-%m-%d %H-%M-%S'
          step: HOUR_TO_SECOND

        name:
          func: default
          value: test

      number: 5
